CREATE TABLE Card (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
cardName VARCHAR(30) NOT NULL,
cardNumber VARCHAR(30) NOT NULL,
cardCvv INT(10) NOT NULL,
cardAddress VARCHAR(50) NOT NULL
);

CREATE TABLE encrypted (
ecardName VARCHAR(100) NOT NULL,
ecardNumber VARCHAR(100) NOT NULL,
ecardCvv VARCHAR(100) NOT NULL,
ecardAddress VARCHAR(100) NOT NULL,
id INT(6) NOT NULL REFERENCES Card
);